name: Launcher Build

on:
  push:
    branches: [ main ]

jobs:
  create-release:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Get version
        run: echo "version=$(jq -r .version package.json)" >> $GITHUB_ENV

      - name: Create Release
        id: create_release
        uses: actions/create-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITH_TOKEN }}
        with:
          tag_name: ${{ env.version }}
          release_name: Version ${{ env.version }}
          draft: false
          prerelease: ${{ contains(env.version, 'beta') || contains(env.version, 'alpha') }}

  build-launcher:
    needs: create-release
    runs-on: ${{ matrix.os }}

    permissions:
      contents: write

    strategy:
      matrix:
        os: [macos-latest, ubuntu-latest, windows-latest]

    steps:
      - name: Check out Git repository
        uses: actions/checkout@v2

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          # Change to a compatible Node.js version
          node-version: '>=19.0.0'

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: 3.x

      - name: Install Dependencies
        run: |
          npm install
        shell: bash

      - name: Build Launcher
        env:
          GITHUB_TOKEN: ${{ secrets.GITH_TOKEN }}
        run: npm run build
        shell: bash

      - name: Upload Build Artefacts
        env:
          GITHUB_TOKEN: ${{ secrets.GITH_TOKEN }}
        run: |
          ls dist # Vérifier le contenu du dossier `dist`
        shell: bash

      - name: Upload to GitHub Release
        uses: actions/upload-release-asset@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITH_TOKEN }}
        with:
          upload_url: ${{ steps.create_release.outputs.upload_url }}
          asset_path: dist/ # Remplacez `dist/` par le chemin exact vers vos fichiers générés
          asset_name: "${{ matrix.os }}_build.zip" # Nommez les artefacts correctement
          asset_content_type: application/zip
